sudo: required
services:
  - docker

before_install:
  - docker build -t humeji/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true USERNAME/react-test npm test

after_success:
  - docker build -t humeji/multi-client ./client
  - docker build -t humeji/multi-ngnix ./ngnix
  - docker build -t humeji/multi-server ./server
  - docker build -t humeji/multi-worker ./worker
# Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
# taks those images and push them to docker hub
  - docker push humeji/multi-client
  - docker push humeji/multi-ngnix
  - docker push humeji/multi-server
  - docker push humeji/multi-worker
